[package]
name = "xdpcidr"
version = "0.1.0"
edition = "2024"
authors = ["Nishant"]
description = "XDP program that drops packets from blocked IPv4 addresses and CIDR ranges"
readme = "README.md"
license = "GPL-2.0-only"
repository = "https://github.com/nishujangra/xdpcidr"
keywords = ["xdp", "ebpf", "aya", "firewall", "cidr"]
categories = ["network-programming"]

[dependencies]
aya = "0.14"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
ipnet = "2"
log = "0.4"
env_logger = "0.11"

[profile.release]
lto = true
codegen-units = 1
strip = true
